### ISSUE TITLE
Image didn't show correctly

### ISSUE THREAD

**Issue by medival** [antonybudianto/wfa-id#1]
I just check on https://wfa-id.vercel.app the image's thumbnail does not show.

![Screen Shot 2022-04-22 at 19 39 35](https://user-images.githubusercontent.com/24785432/164716123-2b127404-70d5-4ead-b1ed-954d63de6c85.png)

**Comment by antonybudianto** [comment]
yes, looks like linkedin already protected those resource unfortunately :|

btw this repo will be archived since it'll be succeeded by https://github.com/jackyef/id-wfa ya, thanks!
